### ISSUE TITLE
debian8下trigger下的异常

### ISSUE THREAD

**Issue by snake1361222** [sohutv/cachecloud#10]
## 异常日志
```
2016-03-17 17:03:00.404 {quartzThreadPool-35} ERROR com.sohu.cache.machine.impl.MachineCenterImpl - SSH error, ip: 172.18.19.153
com.sohu.cache.exception.SSHException: SSH error, ip: 172.18.19.153
        at com.sohu.cache.ssh.SSHUtil.getMachineInfo(SSHUtil.java:77) ~[classes!/:na]
        at com.sohu.cache.machine.impl.MachineCenterImpl.collectMachineInfo(MachineCenterImpl.java:119) ~[classes!/:na]
        at com.sohu.cache.schedule.jobs.MachineJob.action(MachineJob.java:33) [classes!/:na]
        at com.sohu.cache.schedule.jobs.CacheBaseJob.execute(CacheBaseJob.java:34) [classes!/:na]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.2.1.jar!/:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_65]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
Caused by: java.lang.Exception: Error when get system performance of ip: 172.18.19.153
        at com.sohu.cache.ssh.SSHUtil.getMachineInfo(SSHUtil.java:211) ~[classes!/:na]
        at com.sohu.cache.ssh.SSHUtil.getMachineInfo(SSHUtil.java:75) ~[classes!/:na]
        ... 7 common frames omitted
Caused by: java.lang.ArrayIndexOutOfBoundsException: 3
        at com.sohu.cache.ssh.SSHUtil.getMachineInfo(SSHUtil.java:150) ~[classes!/:na]
        ... 8 common frames omitted
```

## 系统环境
```
Linux T-ops-Agent-1 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux
```
```
             total       used       free     shared    buffers     cached
Mem:          3909       1724       2184         40        133       1276
-/+ buffers/cache:        314       3594
Swap:         5090          0       5090
```

**Comment by carlosfu** [comment]
这个是由于我们使用top命令进行机器信息的收集，已经测试过red hat和centos正常。
debian8应该存在不兼容的情况。
