### ISSUE TITLE
运行web项目出现了一个错误 请大神帮忙看一下

### ISSUE THREAD

**Issue by tigersshi** [sohutv/cachecloud#113]
运行时  mvn clean compile install -Plocal成功了
运行 mvn spring-boot:run 出现了一个错误 
请帮忙看一下吧

2017-11-24 16:00:25.552 {main} ERROR org.springframework.boot.SpringApplication - Application startup failed
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:133) ~[spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:764) ~[spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:357) ~[spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:305) ~[spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at com.sohu.cache.app.ApplicationStarter.main(ApplicationStarter.java:19) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:467) [spring-boot-maven-plugin-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
Caused by: org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.getEmbeddedServletContainerFactory(EmbeddedWebApplicationContext.java:185) ~[spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:158) ~[spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:130) ~[spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	... 12 common frames omitted
2017-11-24 16:00:25.554 {main} INFO  o.s.b.logging.ClasspathLoggingApplicationListener - Application failed to start with classpath: [file:/G:/eclipse_new/work/cachecloud/cachecloud-open-web/target/classes/, file:/C:/Users/shiming/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar, file:/C:/Users/shiming/.m2/repository/org/quartz-scheduler/quartz/2.2.1/quartz-2.2.1.jar, file:/C:/Users/shiming/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.3.0/jackson-annotations-2.3.0.jar, file:/C:/Users/shiming/.m2/repository/org/apache/velocity/velocity-tools/2.0/velocity-tools-2.0.jar, file:/C:/Users/shiming/.m2/repository/org/apache/struts/struts-tiles/1.3.8/struts-tiles-1.3.8.jar, file:/C:/Users/shiming/.m2/repository/org/mockito/mockito-core/1.10.19/mockito-core-1.10.19.jar, file:/C:/Users/shiming/.m2/repository/org/eclipse/jdt/core/compiler/ecj/4.4.2/ecj-4.4.2.jar, file:/C:/Users/shiming/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar, file:/C:/Users/shiming/.m2/repository/mysql/mysql-connector-java/5.1.29/mysql-connector-java-5.1.29.jar, file:/C:/Users/shiming/.m2/repository/sslext/sslext/1.2-0/sslext-1.2-0.jar, file:/C:/Users/shiming/.m2/repository/com/sohu/tv/cachecloud-open-client-basic/1.0-SNAPSHOT/cachecloud-open-client-basic-1.0-SNAPSHOT.jar, file:/C:/Users/shiming/.m2/repository/org/springframework/boot/spring-boot-dependencies/1.3.1.RELEASE/spring-boot-dependencies-1.3.1.RELEASE.pom, file:/C:/Users/shiming/.m2/repository/org/apache/tomcat/tomcat-juli/8.0.30/tomcat-juli-8.0.30.jar, file:/C:/Users/shiming/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.3.2/jackson-databind-2.3.2.jar, file:/C:/Users/shiming/.m2/repository/com/dyuproject/protostuff/protostuff-collectionschema/1.0.8/protostuff-collectionschema-1.0.8.jar, file:/C:/Users/shiming/.m2/repository/org/crashub/crash.plugins.cron/1.3.2/crash.plugins.cron-1.3.2.jar, file:/C:/Users/shiming/.m2/repository/org/apache/tomcat/tomcat-jdbc/8.0.30/tomcat-jdbc-8.0.30.jar, file:/C:/Users/shiming/.m2/repository/org/springframework/spring-test/4.2.4.RELEASE/spring-test-4.2.4.RELEASE.jar, file:/C:/Users/shiming/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/1.3.1.RELEASE/spring-boot-starter-tomcat-1.3.1.RELEASE.jar, file:/C:/Users/shiming/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/8.0.30/tomcat-embed-core-8.0.30.jar, file:/C:/Users/shiming/.m2/repository/org/springframework/spring-webmvc/4.2.4.RELEASE/spring-webmvc-4.2.4.RELEASE.jar, file:/C:/Users/shiming/.m2/repository/dom4j/dom4j/1.1/dom4j-1.1.jar, file:/C:/Users/shiming/.m2/repository/org/springframework/boot/spring-boot-starter/1.3.1.RELEASE/spring-boot-starter-1.3.1.RELEASE.jar, file:/C:/Users/shiming/.m2/repository/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar, file:/C:/Users/shiming/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.51/bcprov-jdk15on-1.51.jar, file:/C:/Users/shiming/.m2/repository/org/apache/tomcat/embed/tomcat-embed-logging-juli/8.0.30/tomcat-embed-logging-juli-8.0.30.jar, file:/C:/Users/shiming/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/8.0.30/tomcat-embed-websocket-8.0.30.jar, file:/C:/Users/shiming/.m2/repository/com/dyuproject/protostuff/protostuff-runtime/1.0.8/protostuff-runtime-1.0.8.jar, file:/C:/Users/shiming/.m2/repository/org/springframework/boot/spring-boot-starter-web/1.3.1.RELEASE/spring-boot-starter-web-1.3.1.RELEASE.jar, file:/C:/Users/shiming/.m2/repository/org/mybatis/mybatis/3.2.8/mybatis-3.2.8.jar, file:/C:/Users/shiming/.m2/repository/commons-collections/commons-collections/3.2/commons-collections-3.2.jar, file:/C:/Users/shiming/.m2/repository/c3p0/c3p0/0.9.1.1/c3p0-0.9.1.1.jar, file:/C:/Users/shiming/.m2/repository/org/slf4j/slf4j-api/1.7.6/slf4j-api-1.7.6.jar, file:/C:/Users/shiming/.m2/repository/org/springframework/spring-tx/4.2.4.RELEASE/spring-tx-4.2.4.RELEASE.jar, file:/C:/Users/shiming/.m2/repository/org/springframework/spring-context-support/4.2.4.RELEASE/spring-context-support-4.2.4.RELEASE.jar, file:/C:/Users/shiming/.m2/repository/org/springframework/boot/spring-boot-starter-jdbc/1.3.1.RELEASE/spring-boot-starter-jdbc-1.3.1.RELEASE.jar, file:/C:/Users/shiming/.m2/repository/org/apache/struts/struts-core/1.3.8/struts-core-1.3.8.jar, file:/C:/Users/shiming/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar, file:/C:/Users/shiming/.m2/repository/antlr/antlr/2.7.2/antlr-2.7.2.jar, file:/C:/Users/shiming/.m2/repository/ch/qos/logback/logback-classic/1.1.1/logback-classic-1.1.1.jar, file:/C:/Users/shiming/.m2/repository/org/springframework/boot/spring-boot-starter-test/1.3.1.RELEASE/spring-boot-starter-test-1.3.1.RELEASE.jar, file:/C:/Users/shiming/.m2/repository/commons-chain/commons-chain/1.1/commons-chain-1.1.jar, file:/C:/Users/shiming/.m2/repository/net/sf/json-lib/json-lib/2.2.3/json-lib-2.2.3-jdk15.jar, file:/C:/Users/shiming/.m2/repository/org/springframework/boot/spring-boot/1.3.1.RELEASE/spring-boot-1.3.1.RELEASE.jar, file:/C:/Users/shiming/.m2/repository/it/sauronsoftware/cron4j/cron4j/2.2.5/cron4j-2.2.5.jar, file:/C:/Users/shiming/.m2/repository/com/sohu/tv/cachecloud-jedis/1.0-SNAPSHOT/cachecloud-jedis-1.0-SNAPSHOT.jar, file:/C:/Users/shiming/.m2/repository/commons-beanutils/commons-beanutils-core/1.8.0/commons-beanutils-core-1.8.0.jar, file:/C:/Users/shiming/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar, file:/C:/Users/shiming/.m2/repository/org/apache/httpcomponents/httpclient/4.3.2/httpclient-4.3.2.jar, file:/C:/Users/shiming/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.13/jcl-over-slf4j-1.7.13.jar, file:/C:/Users/shiming/.m2/repository/org/crashub/crash.embed.spring/1.3.2/crash.embed.spring-1.3.2.jar, file:/C:/Users/shiming/.m2/repository/org/springframework/spring-jdbc/4.2.4.RELEASE/spring-jdbc-4.2.4.RELEASE.jar, file:/C:/Users/shiming/.m2/repository/org/springframework/boot/spring-boot-starter-validation/1.3.1.RELEASE/spring-boot-starter-validation-1.3.1.RELEASE.jar, file:/C:/Users/shiming/.m2/repository/oro/oro/2.0.8/oro-2.0.8.jar, file:/C:/Users/shiming/.m2/repository/com/alibaba/fastjson/1.2.28/fastjson-1.2.28.jar, file:/C:/Users/shiming/.m2/repository/org/springframework/spring-expression/4.2.4.RELEASE/spring-expression-4.2.4.RELEASE.jar, file:/C:/Users/shiming/.m2/repository/org/apache/commons/commons-collections4/4.0/commons-collections4-4.0.jar, file:/C:/Users/shiming/.m2/repository/ch/qos/logback/logback-core/1.1.1/logback-core-1.1.1.jar, file:/C:/Users/shiming/.m2/repository/org/springframework/spring-beans/4.2.4.RELEASE/spring-beans-4.2.4.RELEASE.jar, file:/C:/Users/shiming/.m2/repository/org/apache/httpcomponents/httpcore/4.3.1/httpcore-4.3.1.jar, file:/C:/Users/shiming/.m2/repository/org/slf4j/log4j-over-slf4j/1.7.13/log4j-over-slf4j-1.7.13.jar, file:/C:/Users/shiming/.m2/repository/org/hamcrest/hamcrest-library/1.3/hamcrest-library-1.3.jar, file:/C:/Users/shiming/.m2/repository/org/apache/struts/struts-taglib/1.3.8/struts-taglib-1.3.8.jar, file:/C:/Users/shiming/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/8.0.30/tomcat-embed-el-8.0.30.jar, file:/C:/Users/shiming/.m2/repository/org/apache/commons/commons-pool2/2.3/commons-pool2-2.3.jar, file:/C:/Users/shiming/.m2/repository/org/springframework/spring-aop/4.2.4.RELEASE/spring-aop-4.2.4.RELEASE.jar, file:/C:/Users/shiming/.m2/repository/org/springframework/boot/spring-boot-starter-remote-shell/1.3.1.RELEASE/spring-boot-starter-remote-shell-1.3.1.RELEASE.jar, file:/C:/Users/shiming/.m2/repository/com/fasterxml/classmate/1.1.0/classmate-1.1.0.jar, file:/C:/Users/shiming/.m2/repository/org/springframework/boot/spring-boot-actuator/1.3.1.RELEASE/spring-boot-actuator-1.3.1.RELEASE.jar, file:/C:/Users/shiming/.m2/repository/commons-lang/commons-lang/2.3/commons-lang-2.3.jar, file:/C:/Users/shiming/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar, file:/C:/Users/shiming/.m2/repository/org/hibernate/hibernate-validator/5.2.2.Final/hibernate-validator-5.2.2.Final.jar, file:/C:/Users/shiming/.m2/repository/org/slf4j/jul-to-slf4j/1.7.13/jul-to-slf4j-1.7.13.jar, file:/C:/Users/shiming/.m2/repository/org/springframework/spring-web/4.2.4.RELEASE/spring-web-4.2.4.RELEASE.jar, file:/C:/Users/shiming/.m2/repository/org/codehaus/groovy/groovy/2.4.4/groovy-2.4.4.jar, file:/C:/Users/shiming/.m2/repository/commons-codec/commons-codec/1.6/commons-codec-1.6.jar, file:/C:/Users/shiming/.m2/repository/com/sun/mail/javax.mail/1.5.4/javax.mail-1.5.4.jar, file:/C:/Users/shiming/.m2/repository/org/springframework/boot/spring-boot-starter-actuator/1.3.1.RELEASE/spring-boot-starter-actuator-1.3.1.RELEASE.jar, file:/C:/Users/shiming/.m2/repository/org/mybatis/mybatis-spring/1.2.3/mybatis-spring-1.2.3.jar, file:/C:/Users/shiming/.m2/repository/org/yaml/snakeyaml/1.16/snakeyaml-1.16.jar, file:/C:/Users/shiming/.m2/repository/com/sohu/tv/cachecloud-open-common/1.0-SNAPSHOT/cachecloud-open-common-1.0-SNAPSHOT.jar, file:/C:/Users/shiming/.m2/repository/commons-configuration/commons-configuration/1.6/commons-configuration-1.6.jar, file:/C:/Users/shiming/.m2/repository/commons-digester/commons-digester/1.8/commons-digester-1.8.jar, file:/C:/Users/shiming/.m2/repository/commons-beanutils/commons-beanutils/1.7.0/commons-beanutils-1.7.0.jar, file:/C:/Users/shiming/.m2/repository/junit/junit/4.11/junit-4.11.jar, file:/C:/Users/shiming/.m2/repository/com/dyuproject/protostuff/protostuff-core/1.0.8/protostuff-core-1.0.8.jar, file:/C:/Users/shiming/.m2/repository/org/springframework/spring-core/4.2.4.RELEASE/spring-core-4.2.4.RELEASE.jar, file:/C:/Users/shiming/.m2/repository/org/springframework/boot/spring-boot-starter-logging/1.3.1.RELEASE/spring-boot-starter-logging-1.3.1.RELEASE.jar, file:/C:/Users/shiming/.m2/repository/ch/ethz/ganymed/ganymed-ssh2/build210/ganymed-ssh2-build210.jar, file:/C:/Users/shiming/.m2/repository/org/jboss/logging/jboss-logging/3.2.1.Final/jboss-logging-3.2.1.Final.jar, file:/C:/Users/shiming/.m2/repository/org/crashub/crash.plugins.mail/1.3.2/crash.plugins.mail-1.3.2.jar, file:/C:/Users/shiming/.m2/repository/org/objenesis/objenesis/2.1/objenesis-2.1.jar, file:/C:/Users/shiming/.m2/repository/com/google/guava/guava/15.0/guava-15.0.jar, file:/C:/Users/shiming/.m2/repository/org/crashub/crash.connectors.ssh/1.3.2/crash.connectors.ssh-1.3.2.jar, file:/C:/Users/shiming/.m2/repository/org/bouncycastle/bcpkix-jdk15on/1.51/bcpkix-jdk15on-1.51.jar, file:/C:/Users/shiming/.m2/repository/org/apache/mina/mina-core/2.0.7/mina-core-2.0.7.jar, file:/C:/Users/shiming/.m2/repository/com/dyuproject/protostuff/protostuff-api/1.0.8/protostuff-api-1.0.8.jar, file:/C:/Users/shiming/.m2/repository/org/crashub/crash.shell/1.3.2/crash.shell-1.3.2.jar, file:/C:/Users/shiming/.m2/repository/org/crashub/crash.cli/1.3.2/crash.cli-1.3.2.jar, file:/C:/Users/shiming/.m2/repository/org/apache/sshd/sshd-core/0.11.0/sshd-core-0.11.0.jar, file:/C:/Users/shiming/.m2/repository/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar, file:/C:/Users/shiming/.m2/repository/net/sf/ezmorph/ezmorph/1.0.6/ezmorph-1.0.6.jar, file:/C:/Users/shiming/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.3.2/jackson-core-2.3.2.jar, file:/C:/Users/shiming/.m2/repository/net/sf/jpam/jpam/1.1/jpam-1.1.jar, file:/C:/Users/shiming/.m2/repository/org/springframework/spring-context/4.2.4.RELEASE/spring-context-4.2.4.RELEASE.jar, file:/C:/Users/shiming/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/1.3.1.RELEASE/spring-boot-autoconfigure-1.3.1.RELEASE.jar, file:/C:/Users/shiming/.m2/repository/org/apache/sshd/sshd-pam/0.11.0/sshd-pam-0.11.0.jar, file:/C:/Users/shiming/.m2/repository/commons-validator/commons-validator/1.3.1/commons-validator-1.3.1.jar, file:/C:/Users/shiming/.m2/repository/org/apache/tomcat/embed/tomcat-embed-jasper/8.0.28/tomcat-embed-jasper-8.0.28.jar, file:/C:/Users/shiming/.m2/repository/org/apache/velocity/velocity/1.7/velocity-1.7.jar]
[WARNING] 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:467)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:133)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:764)
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:357)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:305)
	at com.sohu.cache.app.ApplicationStarter.main(ApplicationStarter.java:19)
	... 6 more
Caused by: org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.getEmbeddedServletContainerFactory(EmbeddedWebApplicationContext.java:185)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:158)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:130)
	... 12 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.852 s
[INFO] Finished at: 2017-11-24T16:00:25+08:00
[INFO] Final Memory: 27M/414M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.3.1.RELEASE:run (default-cli) on project cachecloud-open-web: An exception occurred while running. null: InvocationTargetException: Unable to start embedded container; nested exception is org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.3.1.RELEASE:run (default-cli) on project cachecloud-open-web: An exception occurred while running. null
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: An exception occurred while running. null
	at org.springframework.boot.maven.AbstractRunMojo$IsolatedThreadGroup.rethrowUncaughtException(AbstractRunMojo.java:438)
	at org.springframework.boot.maven.RunMojo.runWithMavenJvm(RunMojo.java:61)
	at org.springframework.boot.maven.AbstractRunMojo.run(AbstractRunMojo.java:215)
	at org.springframework.boot.maven.AbstractRunMojo.execute(AbstractRunMojo.java:174)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:467)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:133)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:764)
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:357)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:305)
	at com.sohu.cache.app.ApplicationStarter.main(ApplicationStarter.java:19)
	... 6 more
Caused by: org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.getEmbeddedServletContainerFactory(EmbeddedWebApplicationContext.java:185)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:158)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:130)
	... 12 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by shuohao** [comment]
mvn spring-boot:run 要在cachecloud-open-web目录下执行
