### ISSUE TITLE
异常报错

### ISSUE THREAD

**Issue by jiangxianzeng** [sohutv/cachecloud#125]
2018-01-10 20:18:13.063 {machine-pool-thread-75} ERROR com.sohu.cache.machine.impl.MachineCenterImpl - SSH err: There was a problem while connecting to 10.10.30.31:60158
com.sohu.cache.exception.SSHException: SSH err: There was a problem while connecting to 10.10.30.31:60158
	at com.sohu.cache.ssh.SSHTemplate.execute(SSHTemplate.java:61) ~[classes!/:na]
	at com.sohu.cache.ssh.SSHUtil.getMachineInfo(SSHUtil.java:72) ~[classes!/:na]
	at com.sohu.cache.machine.impl.MachineCenterImpl.collectMachineInfo(MachineCenterImpl.java:173) ~[classes!/:na]
	at com.sohu.cache.machine.impl.MachineCenterImpl$1.execute(MachineCenterImpl.java:148) [classes!/:na]
	at com.sohu.cache.machine.impl.MachineCenterImpl$1.execute(MachineCenterImpl.java:145) [classes!/:na]
	at com.sohu.cache.async.KeyCallable.call(KeyCallable.java:22) [classes!/:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
Caused by: java.io.IOException: There was a problem while connecting to 10.10.30.31:60158
	at ch.ethz.ssh2.Connection.connect(Connection.java:699) ~[ganymed-ssh2-build210.jar!/:na]
	at com.sohu.cache.ssh.SSHTemplate.getConnection(SSHTemplate.java:79) ~[classes!/:na]
	at com.sohu.cache.ssh.SSHTemplate.execute(SSHTemplate.java:58) ~[classes!/:na]
	... 9 common frames omitted
Caused by: java.io.IOException: Key exchange was not finished, connection is closed.
	at ch.ethz.ssh2.transport.KexManager.getOrWaitForConnectionInfo(KexManager.java:91) ~[ganymed-ssh2-build210.jar!/:na]
	at ch.ethz.ssh2.transport.TransportManager.getConnectionInfo(TransportManager.java:229) ~[ganymed-ssh2-build210.jar!/:na]
	at ch.ethz.ssh2.Connection.connect(Connection.java:655) ~[ganymed-ssh2-build210.jar!/:na]
	... 11 common frames omitted
Caused by: java.io.IOException: Cannot negotiate, proposals do not match.
	at ch.ethz.ssh2.transport.KexManager.handleMessage(KexManager.java:412) ~[ganymed-ssh2-build210.jar!/:na]
	at ch.ethz.ssh2.transport.TransportManager.receiveLoop(TransportManager.java:753) ~[ganymed-ssh2-build210.jar!/:na]
	at ch.ethz.ssh2.transport.TransportManager$1.run(TransportManager.java:468) ~[ganymed-ssh2-build210.jar!/:na]
	... 1 common frames omitted

**Comment by jiangxianzeng** [comment]
?

**Comment by geekyijun** [comment]
请手动使用ssh 命令连接机器试下。

**Comment by macoli** [comment]
请问这个问题解决了吗？我也是这个问题，手动ssh是没问题的
