### ISSUE TITLE
在cachecloud-open-web下执行 mvn spring-boot:run 后报错: [ERROR] Failed to execute goal on project cachecloud-open-web: Could not resolve dependencies for project com.sohu.tv:cachecloud-open-web:war:1.0-SNAPSHOT

### ISSUE THREAD

**Issue by AirJay** [sohutv/cachecloud#13]
cachecloud-open-parent下执行 mvn clean install 成功
然后在cachecloud-open-web下执行 mvn spring-boot:run 后报错：
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.sohu.tv:cachecloud-open-web:war:1.0-SNAPSHOT
[WARNING] 'dependencies.dependency.scope' for org.springframework.boot:spring-boot-dependencies:pom must be one of [provided, compile, runtime, test, system] but is 'import'. @ line 36, column 20
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building cachecloud-open-web 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> spring-boot-maven-plugin:1.3.1.RELEASE:run (default-cli) > test-compile @ cachecloud-open-web >>>
[WARNING] The POM for com.sohu.tv:cachecloud-open-client-basic:jar:1.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.sohu.tv:cachecloud-jedis:jar:1.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.sohu.tv:cachecloud-open-common:jar:1.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.581 s
[INFO] Finished at: 2016-03-18T12:04:27+08:00
[INFO] Final Memory: 12M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project cachecloud-open-web: Could not resolve dependencies for project com.sohu.tv:cachecloud-open-web:war:1.0-SNAPSHOT: The following artifacts could not be resolved: com.sohu.tv:cachecloud-open-client-basic:jar:1.0-SNAPSHOT, com.sohu.tv:cachecloud-jedis:jar:1.0-SNAPSHOT, com.sohu.tv:cachecloud-open-common:jar:1.0-SNAPSHOT: Could not find artifact com.sohu.tv:cachecloud-open-client-basic:jar:1.0-SNAPSHOT -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project cachecloud-open-web: Could not resolve dependencies for project com.sohu.tv:cachecloud-open-web:war:1.0-SNAPSHOT: The following artifacts could not be resolved: com.sohu.tv:cachecloud-open-client-basic:jar:1.0-SNAPSHOT, com.sohu.tv:cachecloud-jedis:jar:1.0-SNAPSHOT, com.sohu.tv:cachecloud-open-common:jar:1.0-SNAPSHOT: Could not find artifact com.sohu.tv:cachecloud-open-client-basic:jar:1.0-SNAPSHOT
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:352)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:197)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project com.sohu.tv:cachecloud-open-web:war:1.0-SNAPSHOT: The following artifacts could not be resolved: com.sohu.tv:cachecloud-open-client-basic:jar:1.0-SNAPSHOT, com.sohu.tv:cachecloud-jedis:jar:1.0-SNAPSHOT, com.sohu.tv:cachecloud-open-common:jar:1.0-SNAPSHOT: Could not find artifact com.sohu.tv:cachecloud-open-client-basic:jar:1.0-SNAPSHOT
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:211)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
	... 27 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: com.sohu.tv:cachecloud-open-client-basic:jar:1.0-SNAPSHOT, com.sohu.tv:cachecloud-jedis:jar:1.0-SNAPSHOT, com.sohu.tv:cachecloud-open-common:jar:1.0-SNAPSHOT: Could not find artifact com.sohu.tv:cachecloud-open-client-basic:jar:1.0-SNAPSHOT
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
	... 28 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: com.sohu.tv:cachecloud-open-client-basic:jar:1.0-SNAPSHOT, com.sohu.tv:cachecloud-jedis:jar:1.0-SNAPSHOT, com.sohu.tv:cachecloud-open-common:jar:1.0-SNAPSHOT: Could not find artifact com.sohu.tv:cachecloud-open-client-basic:jar:1.0-SNAPSHOT
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	... 29 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.sohu.tv:cachecloud-open-client-basic:jar:1.0-SNAPSHOT
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:434)
	... 31 more

**Comment by geekyijun** [comment]
应该是maven仓库的问题， 试着在没有配置私服的maven下启动。
