### ISSUE TITLE
提示应用部署成功后，后端出现异常

### ISSUE THREAD

**Issue by faceny** [sohutv/cachecloud#136]
![image](https://user-images.githubusercontent.com/9759247/39911248-5844b4c4-552d-11e8-8fd8-28fb56e45fd3.png)

java.io.IOException: Error during SCP transfer.
        at ch.ethz.ssh2.SCPClient.put(SCPClient.java:575) ~[ganymed-ssh2-build210.jar:na]
        at com.sohu.cache.ssh.SSHTemplate$SSHSession.scp(SSHTemplate.java:270) [classes/:na]
        at com.sohu.cache.ssh.SSHTemplate$SSHSession.scpToDir(SSHTemplate.java:284) [classes/:na]
        at com.sohu.cache.ssh.SSHUtil$3.call(SSHUtil.java:213) [classes/:na]
        at com.sohu.cache.ssh.SSHTemplate.execute(SSHTemplate.java:59) [classes/:na]
        at com.sohu.cache.ssh.SSHUtil.scpFileToRemote(SSHUtil.java:211) [classes/:na]
        at com.sohu.cache.ssh.SSHUtil.scpFileToRemote(SSHUtil.java:236) [classes/:na]

**Comment by jacksonrick** [comment]
我的也是。。。

**Comment by geekyijun** [comment]
请检查ssh通信。

**Comment by faceny** [comment]
发现是因为远程服务没有对应的目录
