### ISSUE TITLE
水平扩容第五个节点时候，报错，是有最大节点数限制吗？操作其他应用加节点是没问题的

### ISSUE THREAD

**Issue by xujingbin** [sohutv/cachecloud#146]
2018-07-04 14:06:28.821 {http-nio-8585-exec-61} WARN  com.sohu.cache.web.controller.AppManageController - user admin addHorizontalNodes:10.0.0.
197:6000
2018-07-04 14:06:29.499 {http-nio-8585-exec-61} WARN  com.sohu.cache.redis.impl.RedisDeployCenterImpl - runDeleteNodeShell=rm -rf /opt/cacheclo
ud/data/nodes-6383.conf at host 10.0.0.197
2018-07-04 14:06:29.847 {http-nio-8585-exec-61} WARN  com.sohu.cache.redis.impl.RedisDeployCenterImpl - runInstance-fallback : redis-cli -h 10.
0.0.197 -p 6383 shutdown
2018-07-04 14:06:29.862 {http-nio-8585-exec-61} ERROR com.sohu.cache.redis.impl.RedisCenterImpl - java.net.ConnectException: Connection refused
 (Connection refused)
redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused (Connection refused)
        at redis.clients.jedis.Connection.connect(Connection.java:176) ~[cachecloud-jedis-1.0-SNAPSHOT.jar!/:na]
        at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:87) ~[cachecloud-jedis-1.0-SNAPSHOT.jar!/:na]
        at redis.clients.jedis.Connection.sendCommand(Connection.java:110) ~[cachecloud-jedis-1.0-SNAPSHOT.jar!/:na]
        at redis.clients.jedis.Connection.sendCommand(Connection.java:96) ~[cachecloud-jedis-1.0-SNAPSHOT.jar!/:na]
        at redis.clients.jedis.BinaryClient.info(BinaryClient.java:866) ~[cachecloud-jedis-1.0-SNAPSHOT.jar!/:na]
        at redis.clients.jedis.BinaryJedis.info(BinaryJedis.java:2782) ~[cachecloud-jedis-1.0-SNAPSHOT.jar!/:na]
        at com.sohu.cache.redis.impl.RedisCenterImpl.isMaster(RedisCenterImpl.java:756) ~[classes!/:na]
        at com.sohu.cache.redis.RedisClusterReshard.getMasterNodeList(RedisClusterReshard.java:402) [classes!/:na]
        at com.sohu.cache.redis.RedisClusterReshard.joinCluster(RedisClusterReshard.java:83) [classes!/:na]
        at com.sohu.cache.stats.app.impl.AppDeployCenterImpl.addHorizontalNodes(AppDeployCenterImpl.java:540) [classes!/:na]
        at com.sohu.cache.web.controller.AppManageController.doAddHorizontalNodes(AppManageController.java:220) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]

1、水平扩容第五个节点时候（有尝试加三个机器节点都报错），报错，是有最大节点数限制吗？操作其他应用加节点是没问题的
2、迁移一个节点所有slot到另一台机器节点后，并且把源节点下线后，应用总内存仍然包含旧节点的内存，可以解决这个问题吗

**Comment by dinggel** [comment]
刚测试了另一个应用可以添加第5个节点的， 然后这个是什么报错呢

**Comment by dinggel** [comment]
这问题作者都不回答的吗
