### ISSUE TITLE
本地启动不了

### ISSUE THREAD

**Issue by insight0126** [sohutv/cachecloud#194]
2019-07-18 12:10:07.083 {main} ERROR com.sohu.cache.async.impl.AsyncServiceImpl - machine-pool is assembled
2019-07-18 12:10:07.557 {main} WARN  com.sohu.cache.jmx.ErrorLoggerWatcher - ErrorStatisticsAppender init begin!
2019-07-18 12:10:07.560 {main} WARN  com.sohu.cache.jmx.ErrorLoggerWatcher - ErrorStatisticsAppender init Done!
2019-07-18 12:10:20.421 {QuartzScheduler_CacheCloudScheduler-DESKTOP-5G074LO1563423004748_MisfireHandler} ERROR o.s.scheduling.quartz.LocalDataSourceJobStore - Mis
fireHandler: Error handling misfires: Couldn't store trigger 'instanceAlertValue.instanceAlertValueTrigger' for 'instanceAlertValue.instanceAlertValueJob' job:com.
sohu.cache.schedule.jobs.InstanceAlertValueJob
org.quartz.JobPersistenceException: Couldn't store trigger 'instanceAlertValue.instanceAlertValueTrigger' for 'instanceAlertValue.instanceAlertValueJob' job:com.so
hu.cache.schedule.jobs.InstanceAlertValueJob
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1223) ~[quartz-2.2.1.jar:na]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.doUpdateOfMisfiredTrigger(JobStoreSupport.java:1037) ~[quartz-2.2.1.jar:na]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.recoverMisfiredJobs(JobStoreSupport.java:986) ~[quartz-2.2.1.jar:na]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3187) ~[quartz-2.2.1.jar:na]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:3935) [quartz-2.2.1.jar:na]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:3956) [quartz-2.2.1.jar:na]
Caused by: java.lang.ClassNotFoundException: com.sohu.cache.schedule.jobs.InstanceAlertValueJob
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_152]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_152]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_152]
        at org.springframework.scheduling.quartz.ResourceLoaderClassLoadHelper.loadClass(ResourceLoaderClassLoadHelper.java:78) ~[spring-context-support-4.2.4.RELE
ASE.jar:4.2.4.RELEASE]
        at org.springframework.scheduling.quartz.ResourceLoaderClassLoadHelper.loadClass(ResourceLoaderClassLoadHelper.java:83) ~[spring-context-support-4.2.4.RELE
ASE.jar:4.2.4.RELEASE]
        at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectJobDetail(StdJDBCDelegate.java:852) ~[quartz-2.2.1.jar:na]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1205) ~[quartz-2.2.1.jar:na]
        ... 5 common frames omitted

**Comment by chenshi6379** [comment]
可以参考下系统接入文档 [quick start](https://github.com/sohutv/cachecloud/blob/main/cachecloud-web/src/main/resources/static/wiki/quickstart/index.md)
