### ISSUE TITLE
linux升级了openssh之后SSHUtil 连接不上

### ISSUE THREAD

**Issue by kenqq** [sohutv/cachecloud#215]
2020-07-09 17:33:03.514 {machine-pool-thread-97} ERROR com.sohu.cache.machine.impl.MachineCenterImpl - collectMachineErrorStats=>null
2020-07-09 17:33:03.515 {machine-pool-thread-97} ERROR com.sohu.cache.machine.impl.MachineCenterImpl - SSH err: There was a problem while connecting to 127.0.0.1:22
com.sohu.cache.exception.SSHException: SSH err: There was a problem while connecting to 127.0.0.1:22
        at com.sohu.cache.ssh.SSHTemplate.execute(SSHTemplate.java:63) ~[classes!/:na]
        at com.sohu.cache.ssh.SSHUtil.getMachineInfo(SSHUtil.java:72) ~[classes!/:na]
        at com.sohu.cache.machine.impl.MachineCenterImpl.collectMachineInfo(MachineCenterImpl.java:173) ~[classes!/:na]
        at com.sohu.cache.machine.impl.MachineCenterImpl$1.execute(MachineCenterImpl.java:148) [classes!/:na]
        at com.sohu.cache.machine.impl.MachineCenterImpl$1.execute(MachineCenterImpl.java:145) [classes!/:na]
        at com.sohu.cache.async.KeyCallable.call(KeyCallable.java:22) [classes!/:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_242]
Caused by: java.io.IOException: There was a problem while connecting to 127.0.0.1:22
        at ch.ethz.ssh2.Connection.connect(Connection.java:699) ~[ganymed-ssh2-build210.jar!/:na]
        at com.sohu.cache.ssh.SSHTemplate.getConnection(SSHTemplate.java:81) ~[classes!/:na]
        at com.sohu.cache.ssh.SSHTemplate.execute(SSHTemplate.java:60) ~[classes!/:na]
        ... 9 common frames omitted
Caused by: java.io.IOException: Key exchange was not finished, connection is closed.
        at ch.ethz.ssh2.transport.KexManager.getOrWaitForConnectionInfo(KexManager.java:91) ~[ganymed-ssh2-build210.jar!/:na]
        at ch.ethz.ssh2.transport.TransportManager.getConnectionInfo(TransportManager.java:229) ~[ganymed-ssh2-build210.jar!/:na]
        at ch.ethz.ssh2.Connection.connect(Connection.java:655) ~[ganymed-ssh2-build210.jar!/:na]
        ... 11 common frames omitted
Caused by: java.io.IOException: Cannot negotiate, proposals do not match.
        at ch.ethz.ssh2.transport.KexManager.handleMessage(KexManager.java:412) ~[ganymed-ssh2-build210.jar!/:na]
        at ch.ethz.ssh2.transport.TransportManager.receiveLoop(TransportManager.java:753) ~[ganymed-ssh2-build210.jar!/:na]
        at ch.ethz.ssh2.transport.TransportManager$1.run(TransportManager.java:468) ~[ganymed-ssh2-build210.jar!/:na]
        ... 1 common frames omitted

**Comment by kenqq** [comment]
在/etc/ssh/sshd_config 增加修改如下算法即可解决

KexAlgorithms diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group-exchange-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group1-sha1,curve25519-sha256@libssh.org
