### ISSUE TITLE
2.0版本审批创建redis-sentinel报错

### ISSUE THREAD

**Issue by fanxuanhui** [sohutv/cachecloud#251]
![image](https://user-images.githubusercontent.com/14847145/122660938-13203e80-d1b8-11eb-9b19-15f211cab6fc.png)

错误日志:
2021-06-20 10:48:10.008  WARN 54140 --- [zThreadPool-156] c.s.cache.schedule.jobs.TaskExecuteJob   : TaskExecuteJob start
2021-06-20 10:48:10.009  WARN 54140 --- [zThreadPool-156] c.sohu.cache.task.impl.TaskServiceImpl   : current newTaskQueueList is empty
2021-06-20 10:48:10.009  WARN 54140 --- [zThreadPool-156] c.s.cache.schedule.jobs.TaskExecuteJob   : TaskExecuteJob end, cost time is 1 ms
2021-06-20 10:48:10.009  INFO 54140 --- [zThreadPool-156] o.q.p.history.LoggingJobHistoryPlugin    : Job taskExecuteGroup.taskExecuteJob execution complete at  10:48:10 06/20/2021 and reports: null
2021-06-20 10:48:18.354 ERROR 54140 --- [nio-8080-exec-1] c.s.c.redis.impl.AssistRedisServiceImpl  : Could not get a resource from the pool

redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
        at redis.clients.jedis.util.Pool.getResource(Pool.java:53)
        at redis.clients.jedis.JedisPool.getResource(JedisPool.java:334)
        at com.sohu.cache.redis.impl.AssistRedisServiceImpl.getFromJedisPool(AssistRedisServiceImpl.java:53)
        at com.sohu.cache.redis.impl.AssistRedisServiceImpl.lrange(AssistRedisServiceImpl.java:81)
        at com.sohu.cache.web.controller.TaskController.taskFlowList(TaskController.java:149)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
.......

2021-06-20 10:48:18.354 ERROR 54140 --- [nio-8080-exec-1] c.s.c.redis.impl.AssistRedisServiceImpl  : lrange cc:taskflow:1 0 -1 error null

java.lang.NullPointerException: null
        at com.sohu.cache.redis.impl.AssistRedisServiceImpl.lrange(AssistRedisServiceImpl.java:82)
        at com.sohu.cache.web.controller.TaskController.taskFlowList(TaskController.java:149)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)

**Comment by githubname1024** [comment]
请确认配置文件中是否有配置，cachecloud默认依赖的redis配置，或配置的cachecloud.redis.main.host相关配置项是否是有效可访问的redis服务。

**Comment by sqlcyi2008** [comment]
取消订阅




自然而然
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sohutv/cachecloud"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月8日(星期五) 上午9:57
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [sohutv/cachecloud] 2.0版本审批创建redis-sentinel报错 (#251)





 
请确认配置文件中是否有配置，cachecloud默认依赖的redis配置，或配置的cachecloud.redis.main.host相关配置项是否是有效可访问的redis服务。
