### ISSUE TITLE
ssh登录失败

### ISSUE THREAD

**Issue by GitProBo** [sohutv/cachecloud#29]
使用ssh登录验证是可以登陆的,cache登录失败
com.sohu.cache.exception.SSHException: SSH error, ip: 10.1.100.236
        at com.sohu.cache.ssh.SSHUtil.getMachineInfo(SSHUtil.java:77) ~[classes/:na]
        at com.sohu.cache.machine.impl.MachineCenterImpl.collectMachineInfo(MachineCenterImpl.java:120) ~[classes/:na]
        at com.sohu.cache.schedule.jobs.MachineJob.action(MachineJob.java:33) [classes/:na]
        at com.sohu.cache.schedule.jobs.CacheBaseJob.execute(CacheBaseJob.java:34) [classes/:na]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.2.1.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_45]
        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
Caused by: java.lang.Exception: SSH authentication failed with [ userName: cachecloud, password: cachecloud ] on ip: 10.1.100.236
        at com.sohu.cache.ssh.SSHUtil.getMachineInfo(SSHUtil.java:72) ~[classes/:na]
        ... 7 common frames omitted

**Comment by carlosfu** [comment]
> 使用ssh登录验证是可以登陆的,cache登录失败

从异常看是授权ssh没有访问权限。

请问是否执行过cachecloud-init.sh，如果执行了请确认online.properties或者local.properties中的cachecloud.machine.username和cachecloud.machine.password两个属性和执行cachecloud-init.sh时设置的是一样的。
