### ISSUE TITLE
新建redis 哨兵集群报错

### ISSUE THREAD

**Issue by czxin788** [sohutv/cachecloud#309]
新建redis 哨兵集群报错
···
2023-06-19 17:29:50.280  WARN 111220 --- [e-pool-thread-4] c.sohu.cache.task.impl.TaskServiceImpl   : task 4 init finish, result is 中断
2023-06-19 17:29:50.281  WARN 111220 --- [e-pool-thread-4] c.s.c.redis.impl.AssistRedisServiceImpl  : Please Make sure the file:application-${profile}.yml connection pool is configured correctly !  cachecloud.redis.main.host:127.0.0.1 cachecloud.redis.main.port:6379 cachecloud.redis.main.password:
2023-06-19 17:29:50.281  WARN 111220 --- [e-pool-thread-4] c.s.c.redis.impl.AssistRedisServiceImpl  : rpush cc:taskflow:45 2023-06-19 17:29:50.280 {task-execute-pool-thread-4} WARN TaskServiceImpl  - task 4 init finish, result is 中断 error Could not get a resource from the pool

redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.util.Pool.getResource(Pool.java:84)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:370)
	at com.sohu.cache.redis.impl.AssistRedisServiceImpl.getFromJedisPool(AssistRedisServiceImpl.java:54)
	at com.sohu.cache.redis.impl.AssistRedisServiceImpl.rpush(AssistRedisServiceImpl.java:68)
	at com.sohu.cache.log.TaskFlowRecordAppender.append(TaskFlowRecordAppender.java:36)
	at com.sohu.cache.log.TaskFlowRecordAppender.append(TaskFlowRecordAppender.java:17)
	at ch.qos.logback.core.AppenderBase.doAppend(AppenderBase.java:82)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
	at ch.qos.logback.classic.Logger.warn(Logger.java:716)
	at com.sohu.cache.task.impl.TaskServiceImpl.executeTask(TaskServiceImpl.java:225)
	at com.sohu.cache.task.impl.TaskServiceImpl$1.execute(TaskServiceImpl.java:125)
	at com.sohu.cache.task.impl.TaskServiceImpl$1.execute(TaskServiceImpl.java:120)
	at com.sohu.cache.async.KeyCallable.call(KeyCallable.java:22)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed to create socket.
	at redis.clients.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:110)
	at redis.clients.jedis.Connection.connect(Connection.java:226)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:140)
	at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:310)
	at redis.clients.jedis.BinaryJedis.initializeFromClientConfig(BinaryJedis.java:88)
	at redis.clients.jedis.BinaryJedis.<init>(BinaryJedis.java:293)
	at redis.clients.jedis.Jedis.<init>(Jedis.java:169)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:177)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:889)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:424)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:349)
	at redis.clients.jedis.util.Pool.getResource(Pool.java:75)
	... 20 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at redis.clients.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:80)
	... 31 common frames omitted

···

**Comment by githubname1024** [comment]
@czxin788 你好，截图的报错不是sentinel部署失败的日志，上述日志为WARN级别。
该日志是由于，在部署应用时，默认将日志保持一份到redis（该redis需在cachecloud 配置文件配置正确可访问的redis），如果不配置也可以正常部署，仅是在部署页面无法正常显示部署日志，但在系统日志文件中会正常显示部署日志。
可查看系统其他关键ERROR日志，以便于分析。
