### ISSUE TITLE
sh start.sh启动失败！！！

### ISSUE THREAD

**Issue by qianzhou0905** [sohutv/cachecloud#31]
{main} ERROR org.quartz.impl.StdSchedulerFactory - Couldn't generate instance Id!
org.quartz.SchedulerException: Couldn't get host name!
	at org.quartz.simpl.SimpleInstanceIdGenerator.generateInstanceId(SimpleInstanceIdGenerator.java:36) ~[quartz-2.2.1.jar!/:na]
	at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:1211) [quartz-2.2.1.jar!/:na]
	at org.quartz.impl.StdSchedulerFactory.getScheduler(StdSchedulerFactory.java:1519) [quartz-2.2.1.jar!/:na]
	at org.springframework.scheduling.quartz.SchedulerFactoryBean.createScheduler(SchedulerFactoryBean.java:597) [spring-context-support-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.scheduling.quartz.SchedulerFactoryBean.afterPropertiesSet(SchedulerFactoryBean.java:480) [spring-context-support-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]

**Comment by sohutv** [comment]
<img src="http://i2.itc.cn/20160405/3084_835d996c_0c6a_7c5c_2a2e_981f4fe1354a_1.png"/>
就是一个获取hostname，可以在有问题的机器上测试一下，也可以看看自己的ifconfig和hostname

**Comment by qianzhou0905** [comment]
您好非常感谢您的支持，在hosts添加解析后，正常启动。
