### ISSUE TITLE
配置文件中的redis必须要设置密码吗？

### ISSUE THREAD

**Issue by LonelyBean** [sohutv/cachecloud#331]
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.util.Pool.getResource(Pool.java:84)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:370)
	at com.sohu.cache.redis.impl.AssistRedisServiceImpl.getFromJedisPool(AssistRedisServiceImpl.java:54)
	at com.sohu.cache.redis.impl.AssistRedisServiceImpl.rpush(AssistRedisServiceImpl.java:68)
	at com.sohu.cache.log.TaskFlowRecordAppender.append(TaskFlowRecordAppender.java:36)
	at com.sohu.cache.log.TaskFlowRecordAppender.append(TaskFlowRecordAppender.java:17)
	at ch.qos.logback.core.AppenderBase.doAppend(AppenderBase.java:82)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_2(Logger.java:414)
	at ch.qos.logback.classic.Logger.warn(Logger.java:720)
	at com.sohu.cache.task.impl.TaskServiceImpl.executeTask(TaskServiceImpl.java:220)
	at com.sohu.cache.task.impl.TaskServiceImpl$1.execute(TaskServiceImpl.java:125)
	at com.sohu.cache.task.impl.TaskServiceImpl$1.execute(TaskServiceImpl.java:120)
	at com.sohu.cache.async.KeyCallable.call(KeyCallable.java:22)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: redis.clients.jedis.exceptions.JedisDataException: ERR Client sent AUTH, but no password is set
	at redis.clients.jedis.Protocol.processError(Protocol.java:139)
	at redis.clients.jedis.Protocol.process(Protocol.java:173)
	at redis.clients.jedis.Protocol.read(Protocol.java:227)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:352)
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:270)
	at redis.clients.jedis.BinaryJedis.auth(BinaryJedis.java:2710)
	at redis.clients.jedis.BinaryJedis.initializeFromClientConfig(BinaryJedis.java:95)
	at redis.clients.jedis.BinaryJedis.<init>(BinaryJedis.java:293)
	at redis.clients.jedis.Jedis.<init>(Jedis.java:169)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:177)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:889)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:424)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:349)
	at redis.clients.jedis.util.Pool.getResource(Pool.java:75)
	... 20 common frames omitted

**Comment by githubname1024** [comment]
密码是基本的安全保证。
所提供的报错是用于辅助将部分关键信息保存到redis，以便在cachecloud页面进行查看，报错不会影响正常使用。但建议配置。
如果特殊场景，不需要密码，可以自行下载源码进行更改。
