### ISSUE TITLE
添加服务器error

### ISSUE THREAD

**Issue by finfunnel** [sohutv/cachecloud#4]
2016-03-17 11:48:31.540 {http-nio-8585-exec-4} ERROR c.sohu.cache.machine.impl.MachineDeployCenterImpl - save machineInfo: MachineInfo{id=0, sshUser='cachecloud-open', sshPasswd='cachecloud-open', ip='10.128.8.26', room='sh', mem=4, cpu=8, virtual=0, realIp='', serviceTime=null, faultCount=0, modifyTime=null, warn=0, available=0, type=0, groupId=0, extraDesc=null} to db error.
org.springframework.dao.DataIntegrityViolationException: 
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'service_time' cannot be null
; SQL []; Column 'service_time' cannot be null; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'service_time' cannot be null

我是按着正常：机器管理->添加新机器，是添加了一台实体机。以上是/opt/cachecloud-web/logs/stdout.2016-03-17.log日志抛出

**Comment by sohutv** [comment]
> 2016-03-17 11:48:31.540 {http-nio-8585-exec-4} ERROR c.sohu.cache.machine.impl.MachineDeployCenterImpl - save machineInfo: MachineInfo{id=0, sshUser='cachecloud-open', sshPasswd='cachecloud-open', ip='10.128.8.26', room='sh', mem=4, cpu=8, virtual=0, realIp='', serviceTime=null, faultCount=0, modifyTime=null, warn=0, available=0, type=0, groupId=0, extraDesc=null} to db error.
> org.springframework.dao.DataIntegrityViolationException:

@finfunnel  已经修复，更新一下代码。
应该是由于mysql版本造成的，我们线上没有这个问题。

**Comment by finfunnel** [comment]
添加机器OK，但是根据视频会先在Quartz中会生成定时任务去获取主机信息，才能在机器管理中看到，我用的mysql5.6，到了设定的时间，但是机器管理中仍然没有机器，并且日志报错
2016-03-17 13:26:10.986 {quartzThreadPool-7} ERROR com.sohu.cache.machine.impl.MachineCenterImpl - collectMachineErrorStats=>MachineStats{id=0, hostId=2, ip='10.128.8.26', cpuUsage='0.2%', load='0.00', traffic='0.0', memoryUsageRatio='70.24', memoryFree='4976926720', memoryTotal='16720961536', diskUsageMap={/boot=7%, /home=1%, /dev/shm=0%, /=26%}, createTime=null, modifyTime=null}
2016-03-17 13:26:10.992 {quartzThreadPool-7} ERROR com.sohu.cache.machine.impl.MachineCenterImpl - 
### Error updating database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'modify_time' cannot be null
### The error may involve com.sohu.cache.dao.MachineStatsDao.mergeMachineStats-Inline
### The error occurred while setting parameters
### SQL: insert into machine_statistics           (          ip,host_id,cpu_usage,`load`,traffic,memory_usage_ratio,memory_free,memory_total,modify_time      )         values           (?,?,?,?,?,?,?,?,?)         on duplicate key update            host_id = ?,            cpu_usage = ?,            `load` = ?,            traffic = ?,            memory_usage_ratio = ?,            memory_free = ?,            memory_total = ?,            modify_time = ?
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'modify_time' cannot be null
; SQL []; Column 'modify_time' cannot be null; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'modify_time' cannot be null
org.springframework.dao.DataIntegrityViolationException: 
### Error updating database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'modify_time' cannot be null
### The error may involve com.sohu.cache.dao.MachineStatsDao.mergeMachineStats-Inline
### The error occurred while setting parameters
### SQL: insert into machine_statistics           (          ip,host_id,cpu_usage,`load`,traffic,memory_usage_ratio,memory_free,memory_total,modify_time      )         values           (?,?,?,?,?,?,?,?,?)         on duplicate key update            host_id = ?,            cpu_usage = ?,            `load` = ?,            traffic = ?,            memory_usage_ratio = ?,            memory_free = ?,            memory_total = ?,            modify_time = ?
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'modify_time' cannot be null
; SQL []; Column 'modify_time' cannot be null; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'modify_time' cannot be null
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:85) ~[spring-jdbc-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73) ~[spring-jdbc-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81) ~[spring-jdbc-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:74) ~[mybatis-spring-1.2.3.jar!/:1.2.3]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:399) ~[mybatis-spring-1.2.3.jar!/:1.2.3]
	at com.sun.proxy.$Proxy41.insert(Unknown Source) ~[na:na]

**Comment by carlosfu** [comment]
> 添加机器OK，但是根据视频会先在Quartz中会生成定时任务去获取主机信息，才能在机器管理中看到，我用的mysql5.6，到了设定的时间，但是机器管理中仍然

不好意思，还是mysql版本问题，我们用的5.5.16，线上正常。
更新一下代码 我做了兼容。
