### ISSUE TITLE
水平扩容时遇到的bug

### ISSUE THREAD

**Issue by Chung0921** [sohutv/cachecloud#69]
**问题描述:**
在redis应用当中的某个实例instance下线后
在对该应用执行水平扩容时 会报空指针异常
**问题原因:**
代码中List<InstanceInfo> instanceList = appService.getAppInstanceInfo(appId);
这句会返回该机器的对象,但是返回值中包含了已经下线的对象,所以随后会报空指针......

在随后的for循环中不知为何没有对status为不可用的对象进行跳过操作?

随后在for循环中,继续调用子方法getMachineMemoryDetail()

在这个方法中,machineStatsDao.getMachineStatsByIp()这个方法的调用返回了null.而在下一步中又对返回的结果对象进行了setInfo操作,所以导致了空指针的发生..

不知我表达的是否明确..
在删除机器的时候,我看也并没有对instance_info这个表中的机器进行删除操作.
希望官方再确认一下,如果真的有问题,请在下一版本中进行改进...

建议:
1.在删除机器信息的时候,com.sohu.cache.machine.impl.MachineDeployCenterImpl#removeMachine 这个方法中对instance中的机器信息也进行删除
2.在com.sohu.cache.web.controller.AppManageController#fillAppMachineStat这个方法中对已经删除的机器进行过滤,或者在下层方法中添加对空的校验

下面附堆栈信息:
java.lang.NullPointerException: null
        at com.sohu.cache.machine.impl.MachineCenterImpl.getMachineMemoryDetail(MachineCenterImpl.java:547) ~[classes!/:na]
        at com.sohu.cache.web.controller.AppManageController.fillAppMachineStat(AppManageController.java:557) ~[classes!/:na]
        at com.sohu.cache.web.controller.AppManageController.doInitAppScaleApply(AppManageController.java:364) ~[classes!/:na]

**Comment by Chung0921** [comment]
machine_info

**Comment by githubname1024** [comment]
Thanks for your report. We have fixed it.
