### ISSUE TITLE
这个是啥问题？ SSH err: The kexTimeout (6000 ms) expired

### ISSUE THREAD

**Issue by shibaolan** [sohutv/cachecloud#91]
2017-08-07 10:05:02.128 {inspector-host-pool-thread-5} WARN  com.sohu.cache.redis.impl.RedisCenterImpl - XXX.XXX.XXX.XXX:yyyy error message is java.net.SocketTimeoutException: connect timed out 
2017-08-07 10:05:03.150 {future-observe-thread-1} WARN  com.sohu.cache.async.impl.AsyncServiceImpl - WARNING:future=inspector-host-pool-XXX.XXX.XXX.XXX costTime=2994
2017-08-07 10:05:09.833 {future-observe-thread-1} WARN  com.sohu.cache.async.impl.AsyncServiceImpl - WARNING:future=collect-machine-7-XXX.XXX.XXX.XXX-201708071005 costTime=2826
2017-08-07 10:05:32.010 {machine-pool-thread-32} ERROR com.sohu.cache.machine.impl.MachineCenterImpl - collectMachineErrorStats=>null
2017-08-07 10:05:32.011 {machine-pool-thread-32} ERROR com.sohu.cache.machine.impl.MachineCenterImpl - SSH err: The kexTimeout (6000 ms) expired.
com.sohu.cache.exception.SSHException: SSH err: The kexTimeout (6000 ms) expired.
	at com.sohu.cache.ssh.SSHTemplate.execute(SSHTemplate.java:61) ~[classes!/:na]
	at com.sohu.cache.ssh.SSHUtil.getMachineInfo(SSHUtil.java:72) ~[classes!/:na]
	at com.sohu.cache.machine.impl.MachineCenterImpl.collectMachineInfo(MachineCenterImpl.java:173) ~[classes!/:na]
	at com.sohu.cache.machine.impl.MachineCenterImpl$1.execute(MachineCenterImpl.java:148) [classes!/:na]
	at com.sohu.cache.machine.impl.MachineCenterImpl$1.execute(MachineCenterImpl.java:145) [classes!/:na]
	at com.sohu.cache.async.KeyCallable.call(KeyCallable.java:22) [classes!/:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_141]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_141]
Caused by: java.net.SocketTimeoutException: The kexTimeout (6000 ms) expired.
	at ch.ethz.ssh2.Connection.connect(Connection.java:692) ~[ganymed-ssh2-build210.jar!/:na]
	at com.sohu.cache.ssh.SSHTemplate.getConnection(SSHTemplate.java:79) ~[classes!/:na]
	at com.sohu.cache.ssh.SSHTemplate.execute(SSHTemplate.java:58) ~[classes!/:na]
	... 9 common frames omitted
2017-08-07 10:05:32.011 {future-observe-thread-2} WARN  com.sohu.cache.async.impl.AsyncServiceImpl - WARNING:future=collect-machine-26-XXX.XXX.XXX.XXX-201708071005 costTime=6004
2017-08-07 10:05:32.024 {quartzThreadPool-60} ERROR com.sohu.cache.server.ServerStatusCollector - fetchServerStatus XXX.XXX.XXX.XXX err
com.sohu.cache.exception.SSHException: SSH err: The kexTimeout (6000 ms) expired.
	at com.sohu.cache.ssh.SSHTemplate.execute(SSHTemplate.java:61) ~[classes!/:na]
	at com.sohu.cache.ssh.SSHTemplate.execute(SSHTemplate.java:41) ~[classes!/:na]
	at com.sohu.cache.server.ServerStatusCollector.fetchServerStatus(ServerStatusCollector.java:68) ~[classes!/:na]
	at com.sohu.cache.schedule.jobs.ServerJob.action(ServerJob.java:25) [classes!/:na]
	at com.sohu.cache.schedule.jobs.CacheBaseJob.execute(CacheBaseJob.java:36) [classes!/:na]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.2.1.jar!/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_141]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_141]
Caused by: java.net.SocketTimeoutException: The kexTimeout (6000 ms) expired.
	at ch.ethz.ssh2.Connection.connect(Connection.java:692) ~[ganymed-ssh2-build210.jar!/:na]
	at com.sohu.cache.ssh.SSHTemplate.getConnection(SSHTemplate.java:79) ~[classes!/:na]
	at com.sohu.cache.ssh.SSHTemplate.execute(SSHTemplate.java:58) ~[classes!/:na]
	... 8 common frames omitted

**Comment by geekyijun** [comment]
ssh通信超时导致，CacheCloud通过ssh协议与机器进行通信，完成部署和机器级别监控任务，请检查报错机器cachecloud权限下ssh通信是否正常。

**Comment by AlexPeng19** [comment]
怎么检查，能具体点吗

**Comment by AlexPeng19** [comment]
@geekyijun

**Comment by vosamo** [comment]
> @geekyijun

这个问题我也遇到了，请问解决了吗？

**Comment by vosamo** [comment]
@AlexPeng19 
这个问题我也碰到了，请问解决了吗？
